on:
  repository_dispatch:
    type: [incident_report]
    
    # inputs:
    #   environment:
    #     description: "Choose environment"
    #     required: true
    #     default: "staging"
    #     type: choice
    #     options:
    #       - staging
    #       - products 


jobs:
    handel-incident:
        runs-on: ubuntu-latest
        steps:
            - name: print incident report 
              run: echo "incident report"
 # ${{ inputs.environment }}
